<template>
  <div
    class="grid grid-cols-3 gap-5 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 md:gap-x-28 md:gap-y-14"
  >
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/html-5--v1.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/css3.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/javascript--v1.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/tailwindcss.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/bootstrap.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/material-ui.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/react-native.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/vue-js.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/nextjs.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/redux.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/nodejs.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/mongodb.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/git.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/github--v3.png"
    />
    <img
      data-aos="zoom-in"
      src="https://img.icons8.com/color/144/000000/visual-studio-code-2019.png"
    />
  </div>
</template>
